### ISSUE TITLE
Add Docker support 

### ISSUE THREAD

**Issue by mehmet-karagoz** [mehmet-karagoz/Car-Rent-Design-Pattern-Course#2]
Add built in docker suppert with docker-compose file.

**Comment by mhrnnoi** [comment]
Dear mehmet karagoz,

I recently came across your project on GitHub and noticed that there is an open issue requesting the creation of a Dockerfile and docker-compose for the project. I would be happy to take on this task and create those for the project.

If this is something that you would be interested in, please let me know and I will proceed with creating those  and submitting a pull request.

Thank you for your time and consideration.

Best regards,

mehran noeiaghdam

**Comment by mehmet-karagoz** [comment]
Dear Mehran Noeiaghdam,
Thank you for reaching out and expressing your interest in contributing to my project on GitHub. I appreciate your willingness to create a Dockerfile and docker-compose for the project. It would be great to have those additions.
I would be more than happy to have you proceed with creating the Dockerfile and docker-compose files. Once you have completed them, please submit a pull request so that I can review the changes and merge them into the project.
I appreciate your time and effort in helping improve the project. If you have any questions or need any further information, please feel free to ask.
Best regards,
Mehmet Karagoz
